### ISSUE TITLE
Not working at all.

### ISSUE THREAD

**Issue by arpitux** [shpontex/cropme#3]
I tried to use this plugin but its not working. 

I get below error in browser console:
cropme.min.js:10 Uncaught Error: the argument must be an object or a string

**Comment by arpitux** [comment]
I realized it is compulsory to pass parameter(s) in .cropme() method.

**Comment by BradTheOne** [comment]
1. I can't seem to push through viewport options to change the size of the viewport using the vanilla js implementation. If I change the defaults directly in cropme.js file it works

2.Also I could not get the jquery implementation to work I get the same error as above comment .. @arpitux, please post an example of your implementation so that I may see the compulsory properties to pass through.

3. The zoom button is hidden behind the container if I enable this in the default options in the cropme.js file

**Comment by shpontex** [comment]
hi
im sorry for my late response
it was a problem when using jquery to init the cropme
i fixed it in the 1.3.1 version
please check and let me know
thank you
